"""add order_id to trades

Revision ID: e6a29d72e2aa
Revises: f4de50316205
Create Date: 2026-05-21 21:19:48.384431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6a29d72e2aa'
down_revision: Union[str, Sequence[str], None] = 'f4de50316205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('order_id', sa.Uuid(), nullable=False))
    op.add_column('trades', sa.Column('side', sa.String(length=10), nullable=False))
    op.add_column('trades', sa.Column('price', sa.Float(), nullable=False))
    op.drop_index(op.f('ix_trades_status'), table_name='trades')
    op.create_foreign_key(None, 'trades', 'orders', ['order_id'], ['id'])
    op.drop_column('trades', 'entry_price')
    op.drop_column('trades', 'pnl')
    op.drop_column('trades', 'status')
    op.drop_column('trades', 'exit_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('exit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('trades', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('trades', sa.Column('pnl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('trades', sa.Column('entry_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.create_index(op.f('ix_trades_status'), 'trades', ['status'], unique=False)
    op.drop_column('trades', 'price')
    op.drop_column('trades', 'side')
    op.drop_column('trades', 'order_id')
    # ### end Alembic commands ###
