import orjson

from fastapi import APIRouter
from app.cache.redis import redis_client

router = APIRouter()


@router.get("/signals/recent")
async def get_recent_signals(limit: int = 20):
    """
    Returns the last N trading signals generated by the strategy engine.
    Signals are stored in Redis list `signals_log` (capped at 100).
    """
    raw = await redis_client.lrange("signals_log", 0, limit - 1)
    signals = [orjson.loads(item) for item in raw]
    return signals
